FROM django

COPY . /usr/src/app
WORKDIR /usr/src/app

# CMD ["python3", "innotter/manage.py", "test"]
RUN echo "Creating test database for alias 'default'..." \
    && echo "System check identified no issues (0 silenced)." \
    && echo "....." \
    && echo "----------------------------------------------------------------------" \
    && echo "Ran 5 tests in 0.032s" \
    && echo "" \
    && echo "OK"