version: "3.3"

services:
    django:
        build: .
        container_name: django
        command: ['./entrypoint.sh']
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
        networks:
            - my_network
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        networks:
            - my_network
    tests:
        build:
            context: .
            dockerfile: Dockerfile.test
        container_name: django-tests
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - pgdb
        tty: true
        command: ["python3", "innotter/manage.py", "test"]
        networks:
            - my_network
networks:
    my_network: