version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        # python innotter/manage.py migrate
        # command: python innotter/manage.py makemigrations
        command: bash -c "python innotter/manage.py makemigrations user && python innotter/manage.py makemigrations page && python innotter/manage.py migrate && python innotter/manage.py runserver 0.0.0.0:8000"
        # command: entrypoint.sh
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
