version: "3.3"

services:
    django:
        build: .
        container_name: django
        # python innotter/manage.py migrate
        # command: python innotter/manage.py makemigrations
#        command: bash -c "python innotter/manage.py makemigrations user && python innotter/manage.py makemigr>
        command: ['./entrypoint.sh']
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres